apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - name: vaultName
      value: "todo-secrets"
scopes:
  - todo-backend
  - recurring-task-service
  - notification-service
  - audit-service
