replicaCount: 1

image:
  repository: todo-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 3000
  nodePort: 30000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  NEXT_PUBLIC_API_URL: "http://localhost:8000" # Update for local access
